### ISSUE TITLE
python main.py errors.

### ISSUE THREAD

**Issue by jiapei100** [fomorians/fomoro-starter#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 608, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 592, in _run_fn
    session, None, feed_dict, fetch_list, target_list, None)
tensorflow.python.pywrap_tensorflow.StatusNotOK: Not found: checkpoints/checkpoint-0.tempstate1987510780858549244
         [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, Variable/_12, Variable/Adam/_14, Variable/Adam_1/_16, Variable_1/_18, Variable_1/Adam/_20, Variable_1/Adam_1/_22, Variable_2/_24, Variable_2/Adam/_26, Variable_2/Adam_1/_28, Variable_3/_30, Variable_3/Adam/_32, Variable_3/Adam_1/_34, Variable_4/_36, Variable_4/Adam/_38, Variable_4/Adam_1/_40, Variable_5/_42, Variable_5/Adam/_44, Variable_5/Adam_1/_46, Variable_6/_48, Variable_6/Adam/_50, Variable_6/Adam_1/_52, Variable_7/_54, Variable_7/Adam/_56, Variable_7/Adam_1/_58, beta1_power/_60, beta2_power/_62)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 109, in <module>
    saver.save(sess, checkpoint_path + 'checkpoint', global_step=step)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1035, in save
    {self.saver_def.filename_tensor_name: checkpoint_file})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 333, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 538, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 601, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 623, in _do_call
    e.code)
tensorflow.python.framework.errors.NotFoundError: checkpoints/checkpoint-0.tempstate1987510780858549244
         [[Node: save/save = SaveSlices[T=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/save/tensor_names, save/save/shapes_and_slices, Variable/_12, Variable/Adam/_14, Variable/Adam_1/_16, Variable_1/_18, Variable_1/Adam/_20, Variable_1/Adam_1/_22, Variable_2/_24, Variable_2/Adam/_26, Variable_2/Adam_1/_28, Variable_3/_30, Variable_3/Adam/_32, Variable_3/Adam_1/_34, Variable_4/_36, Variable_4/Adam/_38, Variable_4/Adam_1/_40, Variable_5/_42, Variable_5/Adam/_44, Variable_5/Adam_1/_46, Variable_6/_48, Variable_6/Adam/_50, Variable_6/Adam_1/_52, Variable_7/_54, Variable_7/Adam/_56, Variable_7/Adam_1/_58, beta1_power/_60, beta2_power/_62)]]
Caused by op 'save/save', defined at:
  File "main.py", line 78, in <module>
    saver = tf.train.Saver(max_to_keep=1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 832, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 500, in build
    save_tensor = self._AddSaveOps(filename_tensor, vars_to_save)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 197, in _AddSaveOps
    save = self.save_op(filename_tensor, vars_to_save)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 149, in save_op
    tensor_slices=[vs.slice_spec for vs in vars_to_save])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/io_ops.py", line 171, in _save
    tensors, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 341, in _save_slices
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/op_def_library.py", line 661, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2116, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

**Comment by plutoshe** [comment]
Meet the same question. It might be solved by:
1. Upgrade tensorflow package
2. Make sure the path existed for your "checkpoint_path"
